In [2]:
from google.colab import files
import pandas as pd
uploaded= files.upload()

Saving Messy_Employment_India_Dataset.csv to Messy_Employment_India_Dataset.csv

In [8]:
df=pd.read_csv("Messy_Employment_India_Dataset.csv")

In [9]:
df.head()

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023

In [10]:
text_cols = ['Status','Age Group','Education','Industry','Location','AI Risk']

for col in text_cols:
    df[col] = df[col].str.strip().str.title()

In [12]:
df.head()

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,Employed,25_34,High School,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,Employed,18-24,Diploma,Fintech,Rural,Moderate,NaN,17500.0,1/2/2023
2,Employed,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,Unemployed,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,Low,9.0,19500.0,1/5/2023

In [13]:
df['Age Group'] = df['Age Group'].str.replace('_', '-')

In [14]:
for col in ['Status','Education','Industry','Location','AI Risk','Age Group']:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipython-input-3858525928.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [15]:
df['Years of Experience'].fillna(df['Years of Experience'].median(), inplace=True)

/tmp/ipython-input-3272645494.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Years of Experience'].fillna(df['Years of Experience'].median(), inplace=True)

In [16]:
df['Monthly Salary (INR)'].fillna(df['Monthly Salary (INR)'].median(), inplace=True)

/tmp/ipython-input-2843600641.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Monthly Salary (INR)'].fillna(df['Monthly Salary (INR)'].median(), inplace=True)

In [17]:
df['Date Recorded'] = pd.to_datetime(df['Date Recorded'])

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                2000 non-null   object
 1   Age Group             2000 non-null   object
 2   Education             2000 non-null   object
 3   Industry              2000 non-null   object
 4   Location              2000 non-null   object
 5   AI Risk               2000 non-null   object
 6   Years of Experience   2000 non-null   float64
 7   Monthly Salary (INR)  2000 non-null   float64
 8   Date Recorded         2000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 140.8+ KB

Status                  0
Age Group               0
Education               0
Industry                0
Location                0
AI Risk                 0
Years of Experience     0
Monthly Salary (INR)    0
Date Recorded           0
dtype: int64

In [20]:
df.sample(10)

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
1228,Unemployed,18 To 24,High School,Retail,Urban,High,29.0,6300.0,2026-05-13
1599,Employed,18 To 24,Bachelors,Education,Hyderabad,Low,16.0,77200.0,2027-05-19
1893,Unemployed,18-24,Phd,Finance,Rural,Moderate,8.0,61500.0,2028-03-08
1887,Employed,35 - 44,Master,Retail,Bangalore,High,16.0,77200.0,2028-03-02
840,Employed,45-54,High School,Education,Urban,High,16.0,24200.0,2025-04-20
956,Employed,25-34,Ph.D,Technology,Delhi,Low,20.0,115700.0,2025-08-14
312,Employed,25-34,High School,Retail,Rural,Medium,16.0,21400.0,2023-11-09
1008,Unemployed,18 To 24,High School,Fintech,Suburban,Low,16.0,65700.0,2025-10-05
1533,Employed,55+,Masters,Retail,Urban,High,13.0,98700.0,2027-03-14
1851,Unemployed,18 To 24,Ph.D,Retail,Suburban,Low,16.0,113400.0,2028-01-26

In [21]:
df.to_csv("cleaned_employment_india.csv", index=False)

In [22]:
from google.colab import files
files.download("cleaned_employment_india.csv")